name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Use GitHub Readme Stats
        uses: anuraghazra/github-readme-stats@v1.1.0
        with:
          snake: true
